### Use Cases
- Data fits in memory
- Volume of data not a performance issue
- Ease of using SQL
- Don't need a fully functional SQL Server database

In [2]:
import pandas as pd
from pandasql import sqldf
from pandasql import load_births

births = load_births()

print(sqldf("SELECT * FROM births where births > 250000 limit 5;", locals()))

                         date  births
0  1975-01-01 00:00:00.000000  265775
1  1975-03-01 00:00:00.000000  268849
2  1975-05-01 00:00:00.000000  254545
3  1975-06-01 00:00:00.000000  254096
4  1975-07-01 00:00:00.000000  275163

## Let's try a query that spans multiple lines...

### Note:  This is standard ANSI SQL.

In [2]:
q = """
      select
        date(date) as DOB,
        sum(births) as "Total Births"
      from
        births
      group by
        date
        limit 10;  
"""

print(sqldf(q, locals()))

          DOB  Total Births
0  1975-01-01        265775
1  1975-02-01        241045
2  1975-03-01        268849
3  1975-04-01        247455
4  1975-05-01        254545
5  1975-06-01        254096
6  1975-07-01        275163
7  1975-08-01        281300
8  1975-09-01        270738
9  1975-10-01        265494

In [3]:
print(sqldf(q, globals()))

          DOB  Total Births
0  1975-01-01        265775
1  1975-02-01        241045
2  1975-03-01        268849
3  1975-04-01        247455
4  1975-05-01        254545
5  1975-06-01        254096
6  1975-07-01        275163
7  1975-08-01        281300
8  1975-09-01        270738
9  1975-10-01        265494

In [4]:
# locals vs. globals and making calling pysqldf a bit easier...

def pysqldf(q):
    "add this to your script if you get tired of calling locals()"
    return sqldf(q, globals())

### Note:  RIGHT and FULL OUTER JOINs are not currently supported

In [5]:
print(pysqldf(q))

          DOB  Total Births
0  1975-01-01        265775
1  1975-02-01        241045
2  1975-03-01        268849
3  1975-04-01        247455
4  1975-05-01        254545
5  1975-06-01        254096
6  1975-07-01        275163
7  1975-08-01        281300
8  1975-09-01        270738
9  1975-10-01        265494

## Let's use our own data...
## We'll use pandas to load it in...

In [6]:
pwd

'D:\\DocumentsD\\Presentations\\PythonSQL\\Notebook'

In [7]:
import pandas as pd

filepath = './Data/'

dfcustomer = pd.read_csv(filepath + 'DimCustomer.csv')

In [8]:
dfcustomer.head(3)

,CustomerKey,GeographyKey,CustomerAlternateKey,Title,FirstName,MiddleName,LastName,NameStyle,BirthDate,MaritalStatus,...,EnglishOccupation,SpanishOccupation,FrenchOccupation,HouseOwnerFlag,NumberCarsOwned,AddressLine1,AddressLine2,Phone,DateFirstPurchase,CommuteDistance
0,11000,26,AW00011000,NaN,Jon,V,Yang,0,1971-10-06,M,...,Professional,Profesional,Cadre,1,0,3761 N. 14th St,NaN,1 (11) 500 555-0162,2011-01-19,1-2 Miles
1,11001,37,AW00011001,NaN,Eugene,L,Huang,0,1976-05-10,S,...,Professional,Profesional,Cadre,0,1,2243 W St.,NaN,1 (11) 500 555-0110,2011-01-15,0-1 Miles
2,11002,31,AW00011002,NaN,Ruben,NaN,Torres,0,1971-02-09,M,...,Professional,Profesional,Cadre,1,1,5844 Linden Land,NaN,1 (11) 500 555-0184,2011-01-07,2-5 Miles

## Eliminating the index...

In [9]:
dfcustomer.set_index('CustomerKey',inplace=True)

In [10]:
dfcustomer

,GeographyKey,CustomerAlternateKey,Title,FirstName,MiddleName,LastName,NameStyle,BirthDate,MaritalStatus,Suffix,...,EnglishOccupation,SpanishOccupation,FrenchOccupation,HouseOwnerFlag,NumberCarsOwned,AddressLine1,AddressLine2,Phone,DateFirstPurchase,CommuteDistance
CustomerKey,,,,,,,,,,,,,,,,,,,,,
11000,26,AW00011000,NaN,Jon,V,Yang,0,1971-10-06,M,NaN,...,Professional,Profesional,Cadre,1,0,3761 N. 14th St,NaN,1 (11) 500 555-0162,2011-01-19,1-2 Miles
11001,37,AW00011001,NaN,Eugene,L,Huang,0,1976-05-10,S,NaN,...,Professional,Profesional,Cadre,0,1,2243 W St.,NaN,1 (11) 500 555-0110,2011-01-15,0-1 Miles
11002,31,AW00011002,NaN,Ruben,NaN,Torres,0,1971-02-09,M,NaN,...,Professional,Profesional,Cadre,1,1,5844 Linden Land,NaN,1 (11) 500 555-0184,2011-01-07,2-5 Miles
11003,11,AW00011003,NaN,Christy,NaN,Zhu,0,1973-08-14,S,NaN,...,Professional,Profesional,Cadre,0,1,1825 Village Pl.,NaN,1 (11) 500 555-0162,2010-12-29,5-10 Miles
11004,19,AW00011004,NaN,Elizabeth,NaN,Johnson,0,1979-08-05,S,NaN,...,Professional,Profesional,Cadre,1,4,7553 Harness Circle,NaN,1 (11) 500 555-0131,2011-01-23,1-2 Miles
11005,22,AW00011005,NaN,Julio,NaN,Ruiz,0,1976-08-01,S,NaN,...,Professional,Profesional,Cadre,1,1,7305 Humphrey Drive,NaN,1 (11) 500 555-0151,2010-12-30,5-10 Miles
11006,8,AW00011006,NaN,Janet,G,Alvarez,0,1976-12-02,S,NaN,...,Professional,Profesional,Cadre,1,1,2612 Berry Dr,NaN,1 (11) 500 555-0184,2011-01-24,5-10 Miles
11007,40,AW00011007,NaN,Marco,NaN,Mehta,0,1969-11-06,M,NaN,...,Professional,Profesional,Cadre,1,2,942 Brook Street,NaN,1 (11) 500 555-0126,2011-01-09,0-1 Miles
11008,32,AW00011008,NaN,Rob,NaN,Verhoff,0,1975-07-04,S,NaN,...,Professional,Profesional,Cadre,1,3,624 Peabody Road,NaN,1 (11) 500 555-0164,2011-01-25,10+ Miles
11009,25,AW00011009,NaN,Shannon,C,Carlson,0,1969-09-29,S,NaN,...,Professional,Profesional,Cadre,0,1,3839 Northgate Road,NaN,1 (11) 500 555-0110,2011-01-27,5-10 Miles
11010,22,AW00011010,NaN,Jacquelyn,C,Suarez,0,1969-08-05,S,NaN,...,Professional,Profesional,Cadre,0,1,7800 Corrinne Court,NaN,1 (11) 500 555-0169,2011-01-14,5-10 Miles
11011,22,AW00011011,NaN,Curtis,NaN,Lu,0,1969-05-03,M,NaN,...,Professional,Profesional,Cadre,1,4,1224 Shoenic,NaN,1 (11) 500 555-0117,2010-12-30,10+ Miles
11012,611,AW00011012,NaN,Lauren,M,Walker,0,1979-01-14,M,NaN,...,Management,GestiÃ³n,Direction,1,2,4785 Scott Street,NaN,717-555-0164,2013-03-16,1-2 Miles
11013,543,AW00011013,NaN,Ian,M,Jenkins,0,1979-08-03,M,NaN,...,Management,GestiÃ³n,Direction,1,3,7902 Hudson Ave.,NaN,817-555-0185,2013-04-13,0-1 Miles
11014,634,AW00011014,NaN,Sydney,NaN,Bennett,0,1973-11-06,S,NaN,...,Management,GestiÃ³n,Direction,0,3,9011 Tank Drive,NaN,431-555-0156,2013-03-23,1-2 Miles
11015,301,AW00011015,NaN,Chloe,NaN,Young,0,1984-08-26,S,NaN,...,Skilled Manual,Obrero especializado,Technicien,0,1,244 Willow Pass Road,NaN,208-555-0142,2013-01-18,5-10 Miles
11016,329,AW00011016,NaN,Wyatt,L,Hill,0,1984-10-25,M,NaN,...,Skilled Manual,Obrero especializado,Technicien,1,1,9666 Northridge Ct.,NaN,135-555-0171,2013-02-09,5-10 Miles
11017,39,AW00011017,NaN,Shannon,NaN,Wang,0,1949-12-24,S,NaN,...,Skilled Manual,Obrero especializado,Technicien,1,2,7330 Saddlehill Lane,NaN,1 (11) 500 555-0195,2011-01-12,5-10 Miles
11018,32,AW00011018,NaN,Clarence,D,Rai,0,1955-10-06,S,NaN,...,Clerical,Administrativo,EmployÃ©,1,2,244 Rivewview,NaN,1 (11) 500 555-0137,2011-01-17,5-10 Miles
11019,52,AW00011019,NaN,Luke,L,Lal,0,1983-09-04,S,NaN,...,Skilled Manual,Obrero especializado,Technicien,0,2,7832 Landing Dr,NaN,262-555-0112,2013-02-12,5-10 Miles
11020,53,AW00011020,NaN,Jordan,C,King,0,1984-03-19,S,NaN,...,Skilled Manual,Obrero especializado,Technicien,0,2,7156 Rose Dr.,NaN,550-555-0163,2012-12-29,1-2 Miles
11021,536,AW00011021,NaN,Destiny,NaN,Wilson,0,1984-03-02,S,NaN,...,Skilled Manual,Obrero especializado,Technicien,0,1,8148 W. Lake Dr.,NaN,622-555-0158,2013-01-23,1-2 Miles
11022,609,AW00011022,NaN,Ethan,G,Zhang,0,1984-04-10,M,NaN,...,Skilled Manual,Obrero especializado,Technicien,1,1,1769 Nicholas Drive,NaN,589-555-0185,2013-01-20,5-10 Miles
11023,298,AW00011023,NaN,Seth,M,Edwards,0,1984-04-09,M,NaN,...,Skilled Manual,Obrero especializado,Technicien,1,1,4499 Valley Crest,NaN,452-555-0188,2013-02-17,1-2 Miles
11024,311,AW00011024,NaN,Russell,NaN,Xie,0,1984-03-16,M,NaN,...,Skilled Manual,Obrero especializado,Technicien,1,2,8734 Oxford Place,NaN,746-555-0186,2013-06-27,5-10 Miles
11025,24,AW00011025,NaN,Alejandro,NaN,Beck,0,1951-06-22,M,NaN,...,Clerical,Administrativo,EmployÃ©,1,2,2596 Franklin Canyon Road,NaN,1 (11) 500 555-0178,2011-01-06,1-2 Miles
11026,4,AW00011026,NaN,Harold,NaN,Sai,0,1951-10-01,S,NaN,...,Clerical,Administrativo,EmployÃ©,0,2,8211 Leeds Ct.,NaN,1 (11) 500 555-0131,2011-01-23,1-2 Miles
11027,40,AW00011027,NaN,Jessie,R,Zhao,0,1952-06-05,M,NaN,...,Clerical,Administrativo,EmployÃ©,1,2,213 Valencia Place,NaN,1 (11) 500 555-0184,2011-01-16,5-10 Miles
11028,17,AW00011028,NaN,Jill,NaN,Jimenez,0,1951-10-09,M,NaN,...,Clerical,Administrativo,EmployÃ©,1,2,9111 Rose Ann Ave,NaN,1 (11) 500 555-0116,2011-01-26,1-2 Miles
11029,32,AW00011029,NaN,Jimmy,L,Moreno,0,1952-06-19,M,NaN,...,Clerical,Administrativo,EmployÃ©,1,2,6385 Mark Twain,NaN,1 (11) 500 555-0146,2011-01-19,1-2 Miles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29454,21,AW00029454,NaN,Victoria,NaN,Bradley,0,1983-07-24,M,NaN,...,Manual,Obrero,Ouvrier,1,1,1227 Wesley Court,NaN,1 (11) 500 555-0125,2013-09-14,2-5 Miles
29455,39,AW00029455,NaN,Dawn,D,Zeng,0,1984-01-06,M,NaN,...,Manual,Obrero,Ouvrier,1,1,460 Skyline Dr,NaN,1 (11) 500 555-0161,2013-09-27,2-5 Miles
29456,5,AW00029456,NaN,Lindsay,NaN,She,0,1983-12-25,S,NaN,...,Manual,Obrero,Ouvrier,1,1,8241 Seawind Dr.,NaN,1 (11) 500 555-0142,2013-09-08,2-5 Miles
29457,33,AW00029457,NaN,Cynthia,NaN,Kapoor,0,1984-01-25,S,NaN,...,Manual,Obrero,Ouvrier,0,1,7045 Creekside Drive,NaN,1 (11) 500 555-0180,2013-09-12,2-5 Miles
29458,17,AW00029458,NaN,Danny,M,Moreno,0,1982-08-24,S,NaN,...,Manual,Obrero,Ouvrier,1,1,1170 Shaw Rd,NaN,1 (11) 500 555-0188,2013-09-14,2-5 Miles
29459,25,AW00029459,NaN,Marco,L,Malhotra,0,1982-11-01,S,NaN,...,Manual,Obrero,Ouvrier,0,1,8168 Eaker Way,NaN,1 (11) 500 555-0172,2013-09-19,2-5 Miles
29460,38,AW00029460,NaN,Andres,E,Chander,0,1982-09-12,M,NaN,...,Manual,Obrero,Ouvrier,0,2,6030 Double Court,NaN,1 (11) 500 555-0133,2013-09-06,0-1 Miles
29461,29,AW00029461,NaN,Colin,C,Xu,0,1983-04-08,M,NaN,...,Manual,Obrero,Ouvrier,1,2,1654 Bonari Court,NaN,1 (11) 500 555-0146,2013-10-19,0-1 Miles
29462,26,AW00029462,NaN,Clinton,NaN,Hernandez,0,1985-01-18,S,NaN,...,Clerical,Administrativo,EmployÃ©,1,0,1733 Thistle Circle,NaN,1 (11) 500 555-0189,2013-09-30,0-1 Miles
29463,23,AW00029463,NaN,Lucas,NaN,Gonzales,0,1984-02-17,S,NaN,...,Manual,Obrero,Ouvrier,1,0,6908 Woodchuck Pl.,NaN,1 (11) 500 555-0172,2013-10-09,2-5 Miles
29464,26,AW00029464,NaN,Eugene,NaN,Gao,0,1983-03-05,S,NaN,...,Manual,Obrero,Ouvrier,0,0,4581 Coldwater Drive,NaN,1 (11) 500 555-0177,2013-10-15,1-2 Miles
29465,8,AW00029465,NaN,Roy,NaN,Gill,0,1982-12-17,S,NaN,...,Manual,Obrero,Ouvrier,1,0,4072 South Hampton Road,NaN,1 (11) 500 555-0110,2013-10-20,0-1 Miles
29466,161,AW00029466,NaN,Lance,NaN,Jimenez,0,1949-05-25,M,NaN,...,Clerical,Administrativo,EmployÃ©,1,0,Auf Der Steige 532,NaN,1 (11) 500 555-0126,2011-06-15,0-1 Miles
29467,178,AW00029467,NaN,Monica,J,Mehta,0,1972-10-12,M,NaN,...,Clerical,Administrativo,EmployÃ©,1,0,Bundesallee 2461,NaN,1 (11) 500 555-0121,2011-06-04,0-1 Miles
29468,236,AW00029468,NaN,Jacqueline,H,Morris,0,1972-06-23,M,NaN,...,Clerical,Administrativo,EmployÃ©,0,0,6934 Santa Cruz Dr.,NaN,1 (11) 500 555-0131,2013-06-04,0-1 Miles
29469,264,AW00029469,NaN,Dominique,M,Saunders,0,1977-10-20,M,NaN,...,Clerical,Administrativo,EmployÃ©,0,0,3792 Westwood Ct.,NaN,1 (11) 500 555-0172,2013-06-16,0-1 Miles
29470,221,AW00029470,NaN,Nathan,NaN,Roberts,0,1971-08-22,S,NaN,...,Manual,Obrero,Ouvrier,0,1,"29, boulevard Beau Marchais",NaN,1 (11) 500 555-0111,2013-12-05,1-2 Miles
29471,186,AW00029471,NaN,Dana,NaN,Ortega,0,1965-09-23,S,NaN,...,Manual,Obrero,Ouvrier,0,1,"80, rue de Fontfroide",NaN,1 (11) 500 555-0148,2014-01-21,2-5 Miles
29472,193,AW00029472,NaN,Lacey,M,Sharma,0,1965-09-11,M,NaN,...,Manual,Obrero,Ouvrier,0,1,"21, avenue Reille",NaN,1 (11) 500 555-0178,2013-09-01,1-2 Miles
29473,262,AW00029473,NaN,Carmen,J,Subram,0,1965-11-19,S,NaN,...,Manual,Obrero,Ouvrier,0,0,6467 Buena Vista,NaN,1 (11) 500 555-0129,2013-06-03,2-5 Miles
29474,174,AW00029474,NaN,Jaime,B,Raje,0,1965-04-02,M,NaN,...,Manual,Obrero,Ouvrier,0,1,Potsdamer StraÃŸe 646,NaN,1 (11) 500 555-0174,2011-06-19,0-1 Miles
29475,147,AW00029475,NaN,Jared,A,Ward,0,1976-03-18,S,NaN,...,Manual,Obrero,Ouvrier,0,1,Erftplatz 876,NaN,1 (11) 500 555-0135,2011-06-29,2-5 Miles
29476,147,AW00029476,NaN,Elizabeth,NaN,Bradley,0,1964-12-30,M,NaN,...,Manual,Obrero,Ouvrier,0,1,Nonnendamm 2,NaN,1 (11) 500 555-0177,2011-07-21,0-1 Miles
29477,253,AW00029477,NaN,Neil,N,Ruiz,0,1965-01-02,M,NaN,...,Manual,Obrero,Ouvrier,0,1,P.O. Box 9178,NaN,1 (11) 500 555-0114,2013-06-18,1-2 Miles
29478,269,AW00029478,NaN,Darren,D,Carlson,0,1964-11-21,S,NaN,...,Clerical,Administrativo,EmployÃ©,1,0,5240 Premier Pl.,NaN,1 (11) 500 555-0132,2013-06-26,0-1 Miles
29479,209,AW00029479,NaN,Tommy,L,Tang,0,1969-06-30,M,NaN,...,Clerical,Administrativo,EmployÃ©,1,0,"111, rue Maillard",NaN,1 (11) 500 555-0136,2012-09-04,0-1 Miles
29480,248,AW00029480,NaN,Nina,W,Raji,0,1977-05-06,S,NaN,...,Clerical,Administrativo,EmployÃ©,1,0,9 Katherine Drive,NaN,1 (11) 500 555-0146,2013-07-17,0-1 Miles
29481,120,AW00029481,NaN,Ivan,NaN,Suri,0,1965-07-04,S,NaN,...,Clerical,Administrativo,EmployÃ©,0,0,Knaackstr 4,NaN,1 (11) 500 555-0144,2011-08-13,0-1 Miles
29482,179,AW00029482,NaN,Clayton,NaN,Zhang,0,1964-09-01,M,NaN,...,Clerical,Administrativo,EmployÃ©,1,0,"1080, quai de Grenelle",NaN,1 (11) 500 555-0137,2012-09-18,0-1 Miles
29483,217,AW00029483,NaN,JÃ©sus,L,Navarro,0,1965-06-06,M,NaN,...,Clerical,Administrativo,EmployÃ©,1,0,"244, rue de la Centenaire",NaN,1 (11) 500 555-0141,2012-09-09,0-1 Miles

In [11]:
pysqldf("select * from dfcustomer;")

,CustomerKey,GeographyKey,CustomerAlternateKey,Title,FirstName,MiddleName,LastName,NameStyle,BirthDate,MaritalStatus,...,EnglishOccupation,SpanishOccupation,FrenchOccupation,HouseOwnerFlag,NumberCarsOwned,AddressLine1,AddressLine2,Phone,DateFirstPurchase,CommuteDistance
0,11000,26,AW00011000,None,Jon,V,Yang,0,1971-10-06,M,...,Professional,Profesional,Cadre,1,0,3761 N. 14th St,None,1 (11) 500 555-0162,2011-01-19,1-2 Miles
1,11001,37,AW00011001,None,Eugene,L,Huang,0,1976-05-10,S,...,Professional,Profesional,Cadre,0,1,2243 W St.,None,1 (11) 500 555-0110,2011-01-15,0-1 Miles
2,11002,31,AW00011002,None,Ruben,None,Torres,0,1971-02-09,M,...,Professional,Profesional,Cadre,1,1,5844 Linden Land,None,1 (11) 500 555-0184,2011-01-07,2-5 Miles
3,11003,11,AW00011003,None,Christy,None,Zhu,0,1973-08-14,S,...,Professional,Profesional,Cadre,0,1,1825 Village Pl.,None,1 (11) 500 555-0162,2010-12-29,5-10 Miles
4,11004,19,AW00011004,None,Elizabeth,None,Johnson,0,1979-08-05,S,...,Professional,Profesional,Cadre,1,4,7553 Harness Circle,None,1 (11) 500 555-0131,2011-01-23,1-2 Miles
5,11005,22,AW00011005,None,Julio,None,Ruiz,0,1976-08-01,S,...,Professional,Profesional,Cadre,1,1,7305 Humphrey Drive,None,1 (11) 500 555-0151,2010-12-30,5-10 Miles
6,11006,8,AW00011006,None,Janet,G,Alvarez,0,1976-12-02,S,...,Professional,Profesional,Cadre,1,1,2612 Berry Dr,None,1 (11) 500 555-0184,2011-01-24,5-10 Miles
7,11007,40,AW00011007,None,Marco,None,Mehta,0,1969-11-06,M,...,Professional,Profesional,Cadre,1,2,942 Brook Street,None,1 (11) 500 555-0126,2011-01-09,0-1 Miles
8,11008,32,AW00011008,None,Rob,None,Verhoff,0,1975-07-04,S,...,Professional,Profesional,Cadre,1,3,624 Peabody Road,None,1 (11) 500 555-0164,2011-01-25,10+ Miles
9,11009,25,AW00011009,None,Shannon,C,Carlson,0,1969-09-29,S,...,Professional,Profesional,Cadre,0,1,3839 Northgate Road,None,1 (11) 500 555-0110,2011-01-27,5-10 Miles
10,11010,22,AW00011010,None,Jacquelyn,C,Suarez,0,1969-08-05,S,...,Professional,Profesional,Cadre,0,1,7800 Corrinne Court,None,1 (11) 500 555-0169,2011-01-14,5-10 Miles
11,11011,22,AW00011011,None,Curtis,None,Lu,0,1969-05-03,M,...,Professional,Profesional,Cadre,1,4,1224 Shoenic,None,1 (11) 500 555-0117,2010-12-30,10+ Miles
12,11012,611,AW00011012,None,Lauren,M,Walker,0,1979-01-14,M,...,Management,GestiÃ³n,Direction,1,2,4785 Scott Street,None,717-555-0164,2013-03-16,1-2 Miles
13,11013,543,AW00011013,None,Ian,M,Jenkins,0,1979-08-03,M,...,Management,GestiÃ³n,Direction,1,3,7902 Hudson Ave.,None,817-555-0185,2013-04-13,0-1 Miles
14,11014,634,AW00011014,None,Sydney,None,Bennett,0,1973-11-06,S,...,Management,GestiÃ³n,Direction,0,3,9011 Tank Drive,None,431-555-0156,2013-03-23,1-2 Miles
15,11015,301,AW00011015,None,Chloe,None,Young,0,1984-08-26,S,...,Skilled Manual,Obrero especializado,Technicien,0,1,244 Willow Pass Road,None,208-555-0142,2013-01-18,5-10 Miles
16,11016,329,AW00011016,None,Wyatt,L,Hill,0,1984-10-25,M,...,Skilled Manual,Obrero especializado,Technicien,1,1,9666 Northridge Ct.,None,135-555-0171,2013-02-09,5-10 Miles
17,11017,39,AW00011017,None,Shannon,None,Wang,0,1949-12-24,S,...,Skilled Manual,Obrero especializado,Technicien,1,2,7330 Saddlehill Lane,None,1 (11) 500 555-0195,2011-01-12,5-10 Miles
18,11018,32,AW00011018,None,Clarence,D,Rai,0,1955-10-06,S,...,Clerical,Administrativo,EmployÃ©,1,2,244 Rivewview,None,1 (11) 500 555-0137,2011-01-17,5-10 Miles
19,11019,52,AW00011019,None,Luke,L,Lal,0,1983-09-04,S,...,Skilled Manual,Obrero especializado,Technicien,0,2,7832 Landing Dr,None,262-555-0112,2013-02-12,5-10 Miles
20,11020,53,AW00011020,None,Jordan,C,King,0,1984-03-19,S,...,Skilled Manual,Obrero especializado,Technicien,0,2,7156 Rose Dr.,None,550-555-0163,2012-12-29,1-2 Miles
21,11021,536,AW00011021,None,Destiny,None,Wilson,0,1984-03-02,S,...,Skilled Manual,Obrero especializado,Technicien,0,1,8148 W. Lake Dr.,None,622-555-0158,2013-01-23,1-2 Miles
22,11022,609,AW00011022,None,Ethan,G,Zhang,0,1984-04-10,M,...,Skilled Manual,Obrero especializado,Technicien,1,1,1769 Nicholas Drive,None,589-555-0185,2013-01-20,5-10 Miles
23,11023,298,AW00011023,None,Seth,M,Edwards,0,1984-04-09,M,...,Skilled Manual,Obrero especializado,Technicien,1,1,4499 Valley Crest,None,452-555-0188,2013-02-17,1-2 Miles
24,11024,311,AW00011024,None,Russell,None,Xie,0,1984-03-16,M,...,Skilled Manual,Obrero especializado,Technicien,1,2,8734 Oxford Place,None,746-555-0186,2013-06-27,5-10 Miles
25,11025,24,AW00011025,None,Alejandro,None,Beck,0,1951-06-22,M,...,Clerical,Administrativo,EmployÃ©,1,2,2596 Franklin Canyon Road,None,1 (11) 500 555-0178,2011-01-06,1-2 Miles
26,11026,4,AW00011026,None,Harold,None,Sai,0,1951-10-01,S,...,Clerical,Administrativo,EmployÃ©,0,2,8211 Leeds Ct.,None,1 (11) 500 555-0131,2011-01-23,1-2 Miles
27,11027,40,AW00011027,None,Jessie,R,Zhao,0,1952-06-05,M,...,Clerical,Administrativo,EmployÃ©,1,2,213 Valencia Place,None,1 (11) 500 555-0184,2011-01-16,5-10 Miles
28,11028,17,AW00011028,None,Jill,None,Jimenez,0,1951-10-09,M,...,Clerical,Administrativo,EmployÃ©,1,2,9111 Rose Ann Ave,None,1 (11) 500 555-0116,2011-01-26,1-2 Miles
29,11029,32,AW00011029,None,Jimmy,L,Moreno,0,1952-06-19,M,...,Clerical,Administrativo,EmployÃ©,1,2,6385 Mark Twain,None,1 (11) 500 555-0146,2011-01-19,1-2 Miles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18454,29454,21,AW00029454,None,Victoria,None,Bradley,0,1983-07-24,M,...,Manual,Obrero,Ouvrier,1,1,1227 Wesley Court,None,1 (11) 500 555-0125,2013-09-14,2-5 Miles
18455,29455,39,AW00029455,None,Dawn,D,Zeng,0,1984-01-06,M,...,Manual,Obrero,Ouvrier,1,1,460 Skyline Dr,None,1 (11) 500 555-0161,2013-09-27,2-5 Miles
18456,29456,5,AW00029456,None,Lindsay,None,She,0,1983-12-25,S,...,Manual,Obrero,Ouvrier,1,1,8241 Seawind Dr.,None,1 (11) 500 555-0142,2013-09-08,2-5 Miles
18457,29457,33,AW00029457,None,Cynthia,None,Kapoor,0,1984-01-25,S,...,Manual,Obrero,Ouvrier,0,1,7045 Creekside Drive,None,1 (11) 500 555-0180,2013-09-12,2-5 Miles
18458,29458,17,AW00029458,None,Danny,M,Moreno,0,1982-08-24,S,...,Manual,Obrero,Ouvrier,1,1,1170 Shaw Rd,None,1 (11) 500 555-0188,2013-09-14,2-5 Miles
18459,29459,25,AW00029459,None,Marco,L,Malhotra,0,1982-11-01,S,...,Manual,Obrero,Ouvrier,0,1,8168 Eaker Way,None,1 (11) 500 555-0172,2013-09-19,2-5 Miles
18460,29460,38,AW00029460,None,Andres,E,Chander,0,1982-09-12,M,...,Manual,Obrero,Ouvrier,0,2,6030 Double Court,None,1 (11) 500 555-0133,2013-09-06,0-1 Miles
18461,29461,29,AW00029461,None,Colin,C,Xu,0,1983-04-08,M,...,Manual,Obrero,Ouvrier,1,2,1654 Bonari Court,None,1 (11) 500 555-0146,2013-10-19,0-1 Miles
18462,29462,26,AW00029462,None,Clinton,None,Hernandez,0,1985-01-18,S,...,Clerical,Administrativo,EmployÃ©,1,0,1733 Thistle Circle,None,1 (11) 500 555-0189,2013-09-30,0-1 Miles
18463,29463,23,AW00029463,None,Lucas,None,Gonzales,0,1984-02-17,S,...,Manual,Obrero,Ouvrier,1,0,6908 Woodchuck Pl.,None,1 (11) 500 555-0172,2013-10-09,2-5 Miles
18464,29464,26,AW00029464,None,Eugene,None,Gao,0,1983-03-05,S,...,Manual,Obrero,Ouvrier,0,0,4581 Coldwater Drive,None,1 (11) 500 555-0177,2013-10-15,1-2 Miles
18465,29465,8,AW00029465,None,Roy,None,Gill,0,1982-12-17,S,...,Manual,Obrero,Ouvrier,1,0,4072 South Hampton Road,None,1 (11) 500 555-0110,2013-10-20,0-1 Miles
18466,29466,161,AW00029466,None,Lance,None,Jimenez,0,1949-05-25,M,...,Clerical,Administrativo,EmployÃ©,1,0,Auf Der Steige 532,None,1 (11) 500 555-0126,2011-06-15,0-1 Miles
18467,29467,178,AW00029467,None,Monica,J,Mehta,0,1972-10-12,M,...,Clerical,Administrativo,EmployÃ©,1,0,Bundesallee 2461,None,1 (11) 500 555-0121,2011-06-04,0-1 Miles
18468,29468,236,AW00029468,None,Jacqueline,H,Morris,0,1972-06-23,M,...,Clerical,Administrativo,EmployÃ©,0,0,6934 Santa Cruz Dr.,None,1 (11) 500 555-0131,2013-06-04,0-1 Miles
18469,29469,264,AW00029469,None,Dominique,M,Saunders,0,1977-10-20,M,...,Clerical,Administrativo,EmployÃ©,0,0,3792 Westwood Ct.,None,1 (11) 500 555-0172,2013-06-16,0-1 Miles
18470,29470,221,AW00029470,None,Nathan,None,Roberts,0,1971-08-22,S,...,Manual,Obrero,Ouvrier,0,1,"29, boulevard Beau Marchais",None,1 (11) 500 555-0111,2013-12-05,1-2 Miles
18471,29471,186,AW00029471,None,Dana,None,Ortega,0,1965-09-23,S,...,Manual,Obrero,Ouvrier,0,1,"80, rue de Fontfroide",None,1 (11) 500 555-0148,2014-01-21,2-5 Miles
18472,29472,193,AW00029472,None,Lacey,M,Sharma,0,1965-09-11,M,...,Manual,Obrero,Ouvrier,0,1,"21, avenue Reille",None,1 (11) 500 555-0178,2013-09-01,1-2 Miles
18473,29473,262,AW00029473,None,Carmen,J,Subram,0,1965-11-19,S,...,Manual,Obrero,Ouvrier,0,0,6467 Buena Vista,None,1 (11) 500 555-0129,2013-06-03,2-5 Miles
18474,29474,174,AW00029474,None,Jaime,B,Raje,0,1965-04-02,M,...,Manual,Obrero,Ouvrier,0,1,Potsdamer StraÃŸe 646,None,1 (11) 500 555-0174,2011-06-19,0-1 Miles
18475,29475,147,AW00029475,None,Jared,A,Ward,0,1976-03-18,S,...,Manual,Obrero,Ouvrier,0,1,Erftplatz 876,None,1 (11) 500 555-0135,2011-06-29,2-5 Miles
18476,29476,147,AW00029476,None,Elizabeth,None,Bradley,0,1964-12-30,M,...,Manual,Obrero,Ouvrier,0,1,Nonnendamm 2,None,1 (11) 500 555-0177,2011-07-21,0-1 Miles
18477,29477,253,AW00029477,None,Neil,N,Ruiz,0,1965-01-02,M,...,Manual,Obrero,Ouvrier,0,1,P.O. Box 9178,None,1 (11) 500 555-0114,2013-06-18,1-2 Miles
18478,29478,269,AW00029478,None,Darren,D,Carlson,0,1964-11-21,S,...,Clerical,Administrativo,EmployÃ©,1,0,5240 Premier Pl.,None,1 (11) 500 555-0132,2013-06-26,0-1 Miles
18479,29479,209,AW00029479,None,Tommy,L,Tang,0,1969-06-30,M,...,Clerical,Administrativo,EmployÃ©,1,0,"111, rue Maillard",None,1 (11) 500 555-0136,2012-09-04,0-1 Miles
18480,29480,248,AW00029480,None,Nina,W,Raji,0,1977-05-06,S,...,Clerical,Administrativo,EmployÃ©,1,0,9 Katherine Drive,None,1 (11) 500 555-0146,2013-07-17,0-1 Miles
18481,29481,120,AW00029481,None,Ivan,None,Suri,0,1965-07-04,S,...,Clerical,Administrativo,EmployÃ©,0,0,Knaackstr 4,None,1 (11) 500 555-0144,2011-08-13,0-1 Miles
18482,29482,179,AW00029482,None,Clayton,None,Zhang,0,1964-09-01,M,...,Clerical,Administrativo,EmployÃ©,1,0,"1080, quai de Grenelle",None,1 (11) 500 555-0137,2012-09-18,0-1 Miles
18483,29483,217,AW00029483,None,JÃ©sus,L,Navarro,0,1965-06-06,M,...,Clerical,Administrativo,EmployÃ©,1,0,"244, rue de la Centenaire",None,1 (11) 500 555-0141,2012-09-09,0-1 Miles

In [12]:
dfinternetsales = pd.read_csv(filepath + 'FactInternetSales.csv')
dfinternetsales.dtypes

ProductKey                 int64
OrderDateKey               int64
DueDateKey                 int64
ShipDateKey                int64
CustomerKey                int64
PromotionKey               int64
CurrencyKey                int64
SalesTerritoryKey          int64
SalesOrderNumber          object
SalesOrderLineNumber       int64
RevisionNumber             int64
OrderQuantity              int64
UnitPrice                float64
ExtendedAmount           float64
UnitPriceDiscountPct       int64
DiscountAmount             int64
ProductStandardCost      float64
TotalProductCost         float64
SalesAmount              float64
TaxAmt                   float64
Freight                  float64
CarrierTrackingNumber    float64
CustomerPONumber         float64
OrderDate                 object
DueDate                   object
ShipDate                  object
dtype: object

In [13]:
import pandas as pd
from pandasql import sqldf

print(pysqldf('''select FirstName, LastName, EnglishOccupation as "Job Title" from dfcustomer 
              order by LastName, FirstName limit 5'''))

   FirstName LastName       Job Title
0      Aaron    Adams  Skilled Manual
1       Adam    Adams      Management
2       Alex    Adams  Skilled Manual
3  Alexandra    Adams    Professional
4    Allison    Adams        Clerical

In [14]:
#  Joining dataframes with SQL

query = '''select * 
           from dfcustomer                     c
           left outer join dfinternetsales     s
                on (c.CustomerKey = s.CustomerKey) limit 3'''

pysqldf(query)

,CustomerKey,GeographyKey,CustomerAlternateKey,Title,FirstName,MiddleName,LastName,NameStyle,BirthDate,MaritalStatus,...,ProductStandardCost,TotalProductCost,SalesAmount,TaxAmt,Freight,CarrierTrackingNumber,CustomerPONumber,OrderDate,DueDate,ShipDate
0,11000,26,AW00011000,None,Jon,V,Yang,0,1971-10-06,M,...,13.0863,13.0863,34.99,2.7992,0.8748,None,None,2013-05-03 00:00:00.000,2013-05-15 00:00:00.000,2013-05-10 00:00:00.000
1,11000,26,AW00011000,None,Jon,V,Yang,0,1971-10-06,M,...,1912.1544,1912.1544,3399.99,271.9992,84.9998,None,None,2011-01-19 00:00:00.000,2011-01-31 00:00:00.000,2011-01-26 00:00:00.000
2,11000,26,AW00011000,None,Jon,V,Yang,0,1971-10-06,M,...,1265.6195,1265.6195,2319.99,185.5992,57.9998,None,None,2013-01-18 00:00:00.000,2013-01-30 00:00:00.000,2013-01-25 00:00:00.000